name = "durable-realtime-fs"
main = "src/index.ts"
compatibility_date = "2024-01-29"
node_compat = true

[dev]
port = 8002
local_protocol = "http"

[[durable_objects.bindings]]
name = "REALTIME"
class_name = "Realtime"

[[rules]]
type = "ESModule"
globs = ["**/*.ts"]
# Indicate that you want the Realtime class to be callable as Durable Objects.
[[migrations]]
tag = "v1" # Should be unique for each entry
new_classes = ["Realtime"]
